name: Emtorch Workflow

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:

jobs:
  build:
    name: Check and build package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.14]

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v5
        with:
          path: ~/.local
          key: poetry-install-20260413

      - name: Install Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install --with=dev --no-root

      - name: Run isort
        run: poetry run isort --check .

      - name: Run black
        run: poetry run black --check .

      - name: Run codespell
        run: poetry run codespell

      - name: Run flake8
        run: poetry run flake8 .

      - name: Run mypy
        run: poetry run mypy .

      - name: Run pylint
        run: poetry run pylint .

      - name: Run pytest
        run: poetry run pytest

      - name: Build distribution
        run: poetry build

      - name: Store built distribution
        uses: actions/upload-artifact@v7
        with:
          name: python-package-distributions-${{ matrix.python-version }}
          path: dist/

  publish-to-pypi:
    name: Publish package to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/emtorch
    permissions:
      id-token: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v8
      with:
        name: python-package-distributions-3.14
        path: dist/
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
